function [fitresult, gof] = FitPower2(Allmove, Gammas)
%CREATEFIT(ALLMOVE,GAMMAS)
%  Create a fit.
%
%  Data for 'PowerFit' fit:
%      X Input : Allmove
%      Y Output: Gammas
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 31-Aug-2021 13:29:58


%% Fit: 'PowerFit'.
[xData, yData] = prepareCurveData( Allmove, Gammas );

% Set up fittype and options.
ft = fittype( 'power2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.684049402861045 0.0553526240831783 -5.99731633655642e-06];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'PowerFit' );
h = plot( fitresult, xData, yData );
legend( h, 'Gammas vs. Allmove', 'PowerFit', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'Allmove', 'Interpreter', 'none' );
ylabel( 'Gammas', 'Interpreter', 'none' );
grid on


